# BCI Competition IV 2a ? Cue? 0~4s / Cue? 4s ? 100ms ? 2s ? (N,1,8,500)
# ????????? 1s/40ms ??
dataset: bci2a
loader: load_bci2a_mat

data_glob: "D:/360MoveData/Users/ckgxnn/Desktop/MI/DATA/bci2a/A0*T.mat"

subject_from: stem3

label_map:
  1: [1, 1]
  2: [1, 2]
drop_codes: [3, 4]
make_rest: true
rest_balance: min_left_right

window_mode: slide_2s_hop100
win_sec: 2.0
hop_ms: 100
fs_out: 250

target_chans: [Cz, C3, C4, CP3, FC4, FC3, CP4, CPz]

val_ratio: 0.2
seed: 42

out_dir: "out/bci2a_2s_hop100"
save_full: true
save_split: true
